# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="teste.mp3"
Content-Type: audio/mpeg

< ./teste.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/1e9a20a7-3758-4484-baa4-8e508bd6074a/transcription
Content-Type: application/json

{
  "prompt": "Security, C#"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "1e9a20a7-3758-4484-baa4-8e508bd6074a",
  "temperature": 0.5,
  "template": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}